- name: install mysql server for expense project
  hosts: ansible-mysql
  become: yes
  tasks: 
  - name: to insatll mysql server
    ansible.builtin.package:
     name: mysql-server
     state: installed 
  - name: to start the mysql server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes  