- name: install mysql server for expense project
  hosts: ansible-mysql
  become: yes
  tasks: 
  - name: to install mysql libraries
    ansible.builtin.pip:
     name: PyMySQL
     executable: pip3.9
       

  - name: to insatll mysql server
    ansible.builtin.package:
     name: mysql-server
     state: installed 

  - name: to start the mysql server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes 

  - name: to login to the mysql server with valid username and password
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: ansible-mysql.rajaws82s.shop
    register: mysql_info
    ignore_errors: true

  - name: to display the mysql status
    ansible.builtin.debug:
     msg: "{{ mysql_info }}"     

  - name: to setup username and password
    ansible.builtin.command: " mysql -h ansible-mysql.rajaws82s.shop -u root -pExpenseApp@1 "   
    when: mysql_info.failed is true