- name: To configure the frontend in the expense project
  hosts: ansible-frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
     name: nginx
     state: installed
  - name: Enable the nginx service
    ansible.builtin.service:
     name: nginx
     state: started
    enabled: yes
  - name: delete a directory (Remove the default content that web server is serving)
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent
  - name: create a directory
    ansible.builtin.file:
     path: /usr/share/nginx/html/
     state: directory
  - name: Download the frontend content
    ansible.builtin.get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
     dest: /tmp/frontend.zip
  - name: unzip the downloaded expense frontend file
    ansible.builtin.unarchive:
     src: /tmp/frontend.zip
     dest: /usr/share/nginx/html
     remote_src: yes
  - name: copy the expense.conf configuration file
    ansible.builtin.copy:
     src: expense.conf
     dest: /etc/nginx/default.d/expense.conf  
  - name: restart the nginx service
    ansible.builtin.service:
     name: nginx
     state: restarted

